"""Initial schema migration from MSSQL

Revision ID: 6a8ac00e2f6c
Revises: 
Create Date: 2026-01-22 12:18:07.686166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a8ac00e2f6c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Comments',
    sa.Column('Id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('CreationDate', sa.DateTime(), nullable=False),
    sa.Column('PostId', sa.Integer(), nullable=False),
    sa.Column('Text', sa.Unicode(length=700), nullable=False),
    sa.Column('Score', sa.Integer(), nullable=True),
    sa.Column('UserId', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('Id', name='PK_Comments__Id'),
    schema='dbo'
    )
    op.create_table('Posts',
    sa.Column('Id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('Body', sa.Unicode(), nullable=False),
    sa.Column('CreationDate', sa.DateTime(), nullable=False),
    sa.Column('LastActivityDate', sa.DateTime(), nullable=False),
    sa.Column('PostTypeId', sa.Integer(), nullable=False),
    sa.Column('Score', sa.Integer(), nullable=False),
    sa.Column('ViewCount', sa.Integer(), nullable=False),
    sa.Column('AcceptedAnswerId', sa.Integer(), nullable=True),
    sa.Column('AnswerCount', sa.Integer(), nullable=True),
    sa.Column('ClosedDate', sa.DateTime(), nullable=True),
    sa.Column('CommentCount', sa.Integer(), nullable=True),
    sa.Column('CommunityOwnedDate', sa.DateTime(), nullable=True),
    sa.Column('FavoriteCount', sa.Integer(), nullable=True),
    sa.Column('LastEditDate', sa.DateTime(), nullable=True),
    sa.Column('LastEditorDisplayName', sa.Unicode(length=40), nullable=True),
    sa.Column('LastEditorUserId', sa.Integer(), nullable=True),
    sa.Column('OwnerUserId', sa.Integer(), nullable=True),
    sa.Column('ParentId', sa.Integer(), nullable=True),
    sa.Column('Tags', sa.Unicode(length=150), nullable=True),
    sa.Column('Title', sa.Unicode(length=250), nullable=True),
    sa.PrimaryKeyConstraint('Id', name='PK_Posts__Id'),
    schema='dbo'
    )
    op.create_table('Users',
    sa.Column('Id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('CreationDate', sa.DateTime(), nullable=False),
    sa.Column('DisplayName', sa.Unicode(length=40), nullable=False),
    sa.Column('DownVotes', sa.Integer(), nullable=False),
    sa.Column('LastAccessDate', sa.DateTime(), nullable=False),
    sa.Column('Reputation', sa.Integer(), nullable=False),
    sa.Column('UpVotes', sa.Integer(), nullable=False),
    sa.Column('Views', sa.Integer(), nullable=False),
    sa.Column('AboutMe', sa.Unicode(), nullable=True),
    sa.Column('Age', sa.Integer(), nullable=True),
    sa.Column('EmailHash', sa.Unicode(length=40), nullable=True),
    sa.Column('Location', sa.Unicode(length=100), nullable=True),
    sa.Column('WebsiteUrl', sa.Unicode(length=200), nullable=True),
    sa.Column('AccountId', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('Id', name='PK_Users_Id'),
    schema='dbo'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Users', schema='dbo')
    op.drop_table('Posts', schema='dbo')
    op.drop_table('Comments', schema='dbo')
    # ### end Alembic commands ###
