"""Initial schema migration from MSSQL

Revision ID: c0458e3336ee
Revises: 
Create Date: 2026-01-22 13:34:20.075082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0458e3336ee'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('creationdate', sa.DateTime(), nullable=False),
    sa.Column('postid', sa.Integer(), nullable=False),
    sa.Column('text', sa.Unicode(length=700), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_comments__id'),
    schema='dw__stackoverflow2010__dbo'
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('body', sa.Unicode(), nullable=False),
    sa.Column('creationdate', sa.DateTime(), nullable=False),
    sa.Column('lastactivitydate', sa.DateTime(), nullable=False),
    sa.Column('posttypeid', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('viewcount', sa.Integer(), nullable=False),
    sa.Column('acceptedanswerid', sa.Integer(), nullable=True),
    sa.Column('answercount', sa.Integer(), nullable=True),
    sa.Column('closeddate', sa.DateTime(), nullable=True),
    sa.Column('commentcount', sa.Integer(), nullable=True),
    sa.Column('communityowneddate', sa.DateTime(), nullable=True),
    sa.Column('favoritecount', sa.Integer(), nullable=True),
    sa.Column('lasteditdate', sa.DateTime(), nullable=True),
    sa.Column('lasteditordisplayname', sa.Unicode(length=40), nullable=True),
    sa.Column('lasteditoruserid', sa.Integer(), nullable=True),
    sa.Column('owneruserid', sa.Integer(), nullable=True),
    sa.Column('parentid', sa.Integer(), nullable=True),
    sa.Column('tags', sa.Unicode(length=150), nullable=True),
    sa.Column('title', sa.Unicode(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_posts__id'),
    schema='dw__stackoverflow2010__dbo'
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('creationdate', sa.DateTime(), nullable=False),
    sa.Column('displayname', sa.Unicode(length=40), nullable=False),
    sa.Column('downvotes', sa.Integer(), nullable=False),
    sa.Column('lastaccessdate', sa.DateTime(), nullable=False),
    sa.Column('reputation', sa.Integer(), nullable=False),
    sa.Column('upvotes', sa.Integer(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('aboutme', sa.Unicode(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('emailhash', sa.Unicode(length=40), nullable=True),
    sa.Column('location', sa.Unicode(length=100), nullable=True),
    sa.Column('websiteurl', sa.Unicode(length=200), nullable=True),
    sa.Column('accountid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_users_id'),
    schema='dw__stackoverflow2010__dbo'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users', schema='dw__stackoverflow2010__dbo')
    op.drop_table('posts', schema='dw__stackoverflow2010__dbo')
    op.drop_table('comments', schema='dw__stackoverflow2010__dbo')
    # ### end Alembic commands ###
