"""Initial schema migration

Revision ID: ff4179b55c6b
Revises: 
Create Date: 2026-01-22 14:13:15.263801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff4179b55c6b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('class', sa.Integer(), nullable=False),
    sa.Column('tagbased', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='badges_pkey'),
    schema='dw__stackoverflow2010__dbo'
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creationdate', sa.DateTime(), nullable=False),
    sa.Column('postid', sa.Integer(), nullable=False),
    sa.Column('Text', sa.String(length=700), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='comments_pkey'),
    schema='dw__stackoverflow2010__dbo'
    )
    op.create_table('linktypes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id', name='linktypes_pkey'),
    schema='dw__stackoverflow2010__dbo'
    )
    op.create_table('postlinks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('postid', sa.Integer(), nullable=False),
    sa.Column('relatedpostid', sa.Integer(), nullable=False),
    sa.Column('linktypeid', sa.Integer(), nullable=False),
    sa.Column('creationdate', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='postlinks_pkey'),
    schema='dw__stackoverflow2010__dbo'
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('creationdate', sa.DateTime(), nullable=False),
    sa.Column('lastactivitydate', sa.DateTime(), nullable=False),
    sa.Column('posttypeid', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('viewcount', sa.Integer(), nullable=False),
    sa.Column('acceptedanswerid', sa.Integer(), nullable=True),
    sa.Column('answercount', sa.Integer(), nullable=True),
    sa.Column('closeddate', sa.DateTime(), nullable=True),
    sa.Column('commentcount', sa.Integer(), nullable=True),
    sa.Column('communityowneddate', sa.DateTime(), nullable=True),
    sa.Column('favoritecount', sa.Integer(), nullable=True),
    sa.Column('lasteditdate', sa.DateTime(), nullable=True),
    sa.Column('lasteditordisplayname', sa.String(length=40), nullable=True),
    sa.Column('lasteditoruserid', sa.Integer(), nullable=True),
    sa.Column('owneruserid', sa.Integer(), nullable=True),
    sa.Column('parentid', sa.Integer(), nullable=True),
    sa.Column('tags', sa.String(length=150), nullable=True),
    sa.Column('title', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id', name='posts_pkey'),
    schema='dw__stackoverflow2010__dbo'
    )
    op.create_table('posttypes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id', name='posttypes_pkey'),
    schema='dw__stackoverflow2010__dbo'
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creationdate', sa.DateTime(), nullable=False),
    sa.Column('displayname', sa.String(length=40), nullable=False),
    sa.Column('downvotes', sa.Integer(), nullable=False),
    sa.Column('lastaccessdate', sa.DateTime(), nullable=False),
    sa.Column('reputation', sa.Integer(), nullable=False),
    sa.Column('upvotes', sa.Integer(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('aboutme', sa.Text(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('emailhash', sa.String(length=40), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('websiteurl', sa.String(length=200), nullable=True),
    sa.Column('accountid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    schema='dw__stackoverflow2010__dbo'
    )
    op.create_table('votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('postid', sa.Integer(), nullable=False),
    sa.Column('votetypeid', sa.Integer(), nullable=False),
    sa.Column('creationdate', sa.DateTime(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('bountyamount', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='votes_pkey'),
    schema='dw__stackoverflow2010__dbo'
    )
    op.create_table('votetypes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id', name='votetypes_pkey'),
    schema='dw__stackoverflow2010__dbo'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votetypes', schema='dw__stackoverflow2010__dbo')
    op.drop_table('votes', schema='dw__stackoverflow2010__dbo')
    op.drop_table('users', schema='dw__stackoverflow2010__dbo')
    op.drop_table('posttypes', schema='dw__stackoverflow2010__dbo')
    op.drop_table('posts', schema='dw__stackoverflow2010__dbo')
    op.drop_table('postlinks', schema='dw__stackoverflow2010__dbo')
    op.drop_table('linktypes', schema='dw__stackoverflow2010__dbo')
    op.drop_table('comments', schema='dw__stackoverflow2010__dbo')
    op.drop_table('badges', schema='dw__stackoverflow2010__dbo')
    # ### end Alembic commands ###
