BEGIN;

CREATE TABLE alembic_version (
    version_num VARCHAR(32) NOT NULL, 
    CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num)
);

-- Running upgrade  -> 271675fe5f1c

CREATE TABLE dbo."Comments" (
    "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY (INCREMENT BY 1 START WITH 1), 
    "CreationDate" TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
    "PostId" INTEGER NOT NULL, 
    "Text" VARCHAR(700) NOT NULL, 
    "Score" INTEGER, 
    "UserId" INTEGER, 
    CONSTRAINT "PK_Comments__Id" PRIMARY KEY ("Id")
);

CREATE TABLE dbo."Posts" (
    "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY (INCREMENT BY 1 START WITH 1), 
    "Body" VARCHAR NOT NULL, 
    "CreationDate" TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
    "LastActivityDate" TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
    "PostTypeId" INTEGER NOT NULL, 
    "Score" INTEGER NOT NULL, 
    "ViewCount" INTEGER NOT NULL, 
    "AcceptedAnswerId" INTEGER, 
    "AnswerCount" INTEGER, 
    "ClosedDate" TIMESTAMP WITHOUT TIME ZONE, 
    "CommentCount" INTEGER, 
    "CommunityOwnedDate" TIMESTAMP WITHOUT TIME ZONE, 
    "FavoriteCount" INTEGER, 
    "LastEditDate" TIMESTAMP WITHOUT TIME ZONE, 
    "LastEditorDisplayName" VARCHAR(40), 
    "LastEditorUserId" INTEGER, 
    "OwnerUserId" INTEGER, 
    "ParentId" INTEGER, 
    "Tags" VARCHAR(150), 
    "Title" VARCHAR(250), 
    CONSTRAINT "PK_Posts__Id" PRIMARY KEY ("Id")
);

CREATE TABLE dbo."Users" (
    "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY (INCREMENT BY 1 START WITH 1), 
    "CreationDate" TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
    "DisplayName" VARCHAR(40) NOT NULL, 
    "DownVotes" INTEGER NOT NULL, 
    "LastAccessDate" TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
    "Reputation" INTEGER NOT NULL, 
    "UpVotes" INTEGER NOT NULL, 
    "Views" INTEGER NOT NULL, 
    "AboutMe" VARCHAR, 
    "Age" INTEGER, 
    "EmailHash" VARCHAR(40), 
    "Location" VARCHAR(100), 
    "WebsiteUrl" VARCHAR(200), 
    "AccountId" INTEGER, 
    CONSTRAINT "PK_Users_Id" PRIMARY KEY ("Id")
);

INSERT INTO alembic_version (version_num) VALUES ('271675fe5f1c') RETURNING alembic_version.version_num;

COMMIT;

